# Generated by Django 2.1.5 on 2019-01-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='subject',
            new_name='topic',
        ),
    ]
