# Generated by Django 2.1.5 on 2019-01-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190111_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finished_quiz',
            new_name='Summary',
        ),
    ]
