# Generated by Django 2.1.5 on 2019-01-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('quiz_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Summary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
