# Generated by Django 2.1.5 on 2019-01-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190125_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpost',
            name='quiz_done',
        ),
    ]
