# Generated by Django 2.1.5 on 2019-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_summary_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='questions',
        ),
        migrations.AddField(
            model_name='summary',
            name='questions',
            field=models.ManyToManyField(to='quiz.QuestionPost'),
        ),
    ]
