# Generated by Django 2.1.5 on 2019-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_quizzes',
            field=models.ManyToManyField(null=True, to='quiz.Quiz'),
        ),
    ]
