# Generated by Django 2.1.5 on 2019-01-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190125_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='quiz_taken',
        ),
        migrations.AddField(
            model_name='questionpost',
            name='finished_quizzes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Summary'),
        ),
    ]
