# Generated by Django 2.1.5 on 2019-01-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190111_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_quiz',
            name='date_taken',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='finished_quiz',
            name='quiz_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='finished_quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finished_quiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Student'),
        ),
    ]
