# Generated by Django 2.1.5 on 2019-01-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_quizzes',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
