# Generated by Django 2.1.5 on 2019-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190126_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cca',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='siteTimeDuration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='travelDuration',
            field=models.IntegerField(null=True),
        ),
    ]
