# Generated by Django 2.1.5 on 2019-01-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190126_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='score',
            new_name='studentScore',
        ),
    ]
