# Generated by Django 2.1.5 on 2019-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_machinelearn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearn',
            name='travelTime',
            field=models.IntegerField(null=True),
        ),
    ]
