# Generated by Django 2.1.5 on 2019-01-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20190127_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='pumpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needHelp', models.CharField(max_length=3)),
            ],
        ),
    ]
