# Generated by Django 2.1.5 on 2019-01-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_pumpmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('hours', models.IntegerField(default=0)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='pumpmodel',
            name='needHelp',
            field=models.CharField(max_length=100),
        ),
    ]
