# Generated by Django 2.1.5 on 2019-01-28 08:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20190128_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='studymodel',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studymodel',
            name='hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Subject'),
        ),
    ]
