# Generated by Django 2.1.5 on 2019-01-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20190129_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
    ]
