# Generated by Django 2.1.5 on 2019-01-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20190129_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schoolSup',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='activities',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='higher',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3),
        ),
    ]
