# Generated by Django 2.1.5 on 2019-01-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20190129_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='sex',
        ),
    ]
